name: release
on: push
jobs:
  Release:
    runs-on: ubuntu-18.04
    container: 
      image: nvcr.io/nvidia/tensorrt:20.03-py3
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build
          cd build 
          cmake ..
          make -j4
      - name: unit-test
        run: ./test/unittest
